services:
  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5


  legacy-app:
    build: ../legacy-app
    restart: unless-stopped
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    volumes:
      - ./legacy-app/data:/legacy-app/data
    depends_on:
      postgres:
        condition: service_healthy

  microservice-app:
    build: ../microservicio-app
    restart: unless-stopped
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    volumes:
      - ./microservice-app/data:/microservice-app/data
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: