apiVersion: apps/v1
kind: Deployment
metadata:
  name: legacy
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      pod: legacy-pod
  template:
    metadata:
      labels:
        pod: legacy-pod
    spec:
      containers:
      - name: legacy-container
        image: legacy:0.1.0
        imagePullPolicy: Never