apiVersion: apps/v1
kind: Deployment
metadata:
  name: legacy
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      pod: legacy-pod
  template:
    metadata:
      labels:
        pod: legacy-pod
    spec:
      containers:
      - name: legacy-container
        image: legacy:0.1.0
        imagePullPolicy: Never # porque son imagenes locales
        envFrom:
          - configMapRef:
              name: configmap
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      pod: microservice-pod
  template:
    metadata:
      labels:
        pod: microservice-pod
    spec:
      containers:
      - name: microservice-container
        image: microservice:0.1.0
        imagePullPolicy: Never
